# Generated by Django 5.2.1 on 2025-10-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('numero', models.CharField(max_length=25)),
                ('calle', models.CharField(max_length=50)),
                ('cantidad_bidones', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('en espera', 'en espera'), ('en camino', 'en camino'), ('entregado', 'entregado')], default='espera', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('cantidad_bidones', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('espera', 'En espera'), ('camino', 'En camino'), ('entregado', 'Entregado')], default='espera', max_length=20)),
            ],
        ),
    ]
