# Generated by Django 5.2.1 on 2025-10-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaturApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('Repartidor', 'Repartidor'), ('Administrador', 'Administrador'), ('Atención al Cliente', 'Atención al Cliente')], max_length=50)),
            ],
        ),
    ]
