# Generated by Django 5.2.1 on 2025-10-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaturApp', '0003_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en espera', 'en espera'), ('en camino', 'en camino'), ('entregado', 'entregado')], default='en espera', max_length=30),
        ),
    ]
