# Generated by Django 5.2.1 on 2025-10-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaturApp', '0004_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('espera', 'En espera'), ('camino', 'En camino'), ('entregado', 'Entregado')], default='En espera', max_length=30),
        ),
    ]
